# Generated by Django 2.2.5 on 2020-01-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actionmenee',
            fields=[
                ('action', models.CharField(max_length=144, null=True, verbose_name='action')),
                ('action_id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='action_id')),
                ('action_autre', models.CharField(max_length=144, null=True, verbose_name='action_autre')),
            ],
        ),
        migrations.CreateModel(
            name='Ministeres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_public', models.CharField(max_length=150, null=True, verbose_name='responsable_public')),
                ('departement_ministeriel', models.CharField(max_length=150, verbose_name='departement_ministriel')),
                ('action_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.Actionmenee', verbose_name='action_id')),
            ],
        ),
        migrations.CreateModel(
            name='Benificiares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire', models.CharField(max_length=155, null=True, verbose_name='beneficiaire')),
                ('en_propre', models.BooleanField(blank=True, null=True, verbose_name='en_propre')),
                ('action_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.Actionmenee', verbose_name='action_id')),
            ],
        ),
    ]
