# Generated by Django 2.2.5 on 2020-01-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HATVP_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='action_menee')),
                ('more', models.TextField(verbose_name='action_menee_autre')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='activite_id')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date_publication_activite')),
                ('ref', models.CharField(max_length=8, verbose_name='identifiant_fiche')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='denomination_affiliation')),
                ('nif', models.CharField(max_length=16, verbose_name='identifiant_national_affiliation')),
                ('nif_type', models.CharField(max_length=16, verbose_name='type_identifiant_national_affiliation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('civility', models.CharField(max_length=8, verbose_name='civilite_collaborateur')),
                ('function', models.CharField(max_length=256, verbose_name='fonction_collaborateur')),
                ('lastname', models.CharField(max_length=64, verbose_name='nom_collaborateur')),
                ('firstname', models.CharField(max_length=64, verbose_name='prenom_collaborateur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='action_menee')),
                ('own', models.BooleanField(default=False, verbose_name='action_menee_en_propre')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='denomination_client')),
                ('nif', models.CharField(max_length=16, verbose_name='identifiant_national_client')),
                ('nif_type', models.CharField(max_length=16, verbose_name='type_identifiant_national_client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='decision_concernee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('civility', models.CharField(max_length=8, verbose_name='civilite_dirigeant')),
                ('function', models.CharField(max_length=256, verbose_name='fonction_dirigeant')),
                ('lastname', models.CharField(max_length=64, verbose_name='nom_dirigeant')),
                ('firstname', models.CharField(max_length=64, verbose_name='prenom_dirigeant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='domaines_intervention_actions_menees')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.Activity', verbose_name='activite_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='secteur_activite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='representants_id')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='adresse')),
                ('zipcode', models.CharField(blank=True, max_length=256, verbose_name='code_postal')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='derniere_publication_activite')),
                ('first_activity', models.DateTimeField(blank=True, null=True, verbose_name='date_premiere_publication')),
                ('organizations', models.BooleanField(default=False, verbose_name='declaration_organisation_appartenance')),
                ('third_parties', models.BooleanField(default=False, verbose_name='declaration_tiers')),
                ('name', models.CharField(max_length=256, verbose_name='denomination')),
                ('nif', models.CharField(max_length=256, unique=True, verbose_name='identifiant_national')),
                ('activities', models.BooleanField(default=False, verbose_name='activites_publiees')),
                ('facebook', models.URLField(blank=True, verbose_name='page_facebook')),
                ('linkedin', models.URLField(blank=True, verbose_name='page_linkedin')),
                ('twitter', models.URLField(blank=True, verbose_name='page_twitter')),
                ('website', models.URLField(blank=True, verbose_name='site_web')),
                ('hatvp_name', models.CharField(max_length=256, verbose_name='nom_usage_HATVP')),
                ('country', models.CharField(max_length=32, verbose_name='pays')),
                ('acronym', models.CharField(max_length=32, verbose_name='sigle_HATVP')),
                ('nif_type', models.CharField(max_length=8, verbose_name='type_identifiant_national')),
                ('town', models.CharField(max_length=64, verbose_name='ville')),
                ('category', models.CharField(max_length=64, verbose_name='label_categorie_organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('1', 'Local'), ('2', 'National'), ('3', 'Européen'), ('4', 'Mondial')], max_length=1, verbose_name='niveau_intervention')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.GeneralInformation', verbose_name='representants_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=128, verbose_name='activite_id')),
                ('observation', models.TextField(verbose_name='observation')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.GeneralInformation', verbose_name='action_representation_interet_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='exercices_id')),
                ('incomplete_declaration', models.BooleanField(default=False, verbose_name='declaration_incomplete')),
                ('publication', models.DateField(blank=True, null=True, verbose_name='date_publication')),
                ('amount', models.CharField(max_length=128, verbose_name='montant_depense')),
                ('min_amount', models.FloatField(verbose_name='montant_depense_inf')),
                ('max_amount', models.FloatField(verbose_name='montant_depense_sup')),
                ('no_activity', models.BooleanField(default=False, verbose_name='exercice_sans_activite')),
                ('nb_activities', models.PositiveIntegerField(default=0, verbose_name='nombre_activites')),
                ('start', models.DateField(blank=True, null=True, verbose_name='date_debut')),
                ('end', models.DateField(blank=True, null=True, verbose_name='date_fin')),
                ('start_year', models.PositiveIntegerField(verbose_name='annee_debut')),
                ('end_year', models.PositiveIntegerField(verbose_name='annee_fin')),
                ('nb_employees', models.FloatField(default=0, verbose_name='nombre_salaries')),
                ('no_turnover', models.BooleanField(default=False, verbose_name='exercice_sans_CA')),
                ('turnover', models.CharField(max_length=128, verbose_name='chiffre_affaires')),
                ('min_turnover', models.FloatField(verbose_name='ca_inf')),
                ('max_turnover', models.FloatField(verbose_name='ca_sup')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.GeneralInformation', verbose_name='representants_id')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='responsable_public')),
                ('department', models.CharField(max_length=128, verbose_name='departement_ministeriel')),
                ('more', models.CharField(max_length=128, verbose_name='responsable_public_ou_dpt_ministeriel_autre')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.GeneralInformation', verbose_name='action_representation_interet_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='benificiares',
            name='action_id',
        ),
        migrations.RemoveField(
            model_name='ministeres',
            name='action_id',
        ),
        migrations.DeleteModel(
            name='Actionmenee',
        ),
        migrations.DeleteModel(
            name='Benificiares',
        ),
        migrations.DeleteModel(
            name='Ministeres',
        ),
        migrations.AddField(
            model_name='field',
            name='representant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.GeneralInformation', verbose_name='representants_id'),
        ),
        migrations.AddField(
            model_name='director',
            name='representant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.GeneralInformation', verbose_name='representants_id'),
        ),
        migrations.AddField(
            model_name='decision',
            name='representant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.GeneralInformation', verbose_name='action_representation_interet_id'),
        ),
        migrations.AddField(
            model_name='client',
            name='representant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.GeneralInformation', verbose_name='representants_id'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='representant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.GeneralInformation', verbose_name='action_representation_interet_id'),
        ),
        migrations.AddField(
            model_name='associate',
            name='representant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.GeneralInformation', verbose_name='representants_id'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='representant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.GeneralInformation', verbose_name='representants_id'),
        ),
        migrations.AddField(
            model_name='activity',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.Period', verbose_name='exercices_id'),
        ),
        migrations.AddField(
            model_name='action',
            name='representant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HATVP_app.GeneralInformation', verbose_name='action_representation_interet_id'),
        ),
    ]
