# Generated by Django 2.2.5 on 2020-01-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HATVP_app', '0002_auto_20200127_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='category',
            field=models.CharField(max_length=256, verbose_name='label_categorie_organisation'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='town',
            field=models.CharField(max_length=256, verbose_name='ville'),
        ),
    ]
