# Generated by Django 2.2.5 on 2020-01-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HATVP_app', '0003_auto_20200127_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='acronym',
            field=models.CharField(max_length=256, verbose_name='sigle_HATVP'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='country',
            field=models.CharField(max_length=256, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='nif_type',
            field=models.CharField(max_length=256, verbose_name='type_identifiant_national'),
        ),
    ]
