# Generated by Django 2.2.5 on 2020-01-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HATVP_app', '0006_auto_20200127_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='name',
            field=models.CharField(max_length=128, verbose_name='beneficiaire_action_menee'),
        ),
    ]
