# Generated by Django 2.2.5 on 2020-01-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HATVP_app', '0007_auto_20200127_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='name',
            field=models.CharField(max_length=256, verbose_name='decision_concernee'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='activity',
            field=models.CharField(max_length=256, verbose_name='activite_id'),
        ),
        migrations.AlterField(
            model_name='target',
            name='department',
            field=models.CharField(max_length=256, verbose_name='departement_ministeriel'),
        ),
        migrations.AlterField(
            model_name='target',
            name='more',
            field=models.CharField(max_length=256, verbose_name='responsable_public_ou_dpt_ministeriel_autre'),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=256, verbose_name='responsable_public'),
        ),
    ]
