# Generated by Django 2.2.5 on 2020-01-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HATVP_app', '0008_auto_20200127_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='department',
            field=models.CharField(max_length=2560, verbose_name='departement_ministeriel'),
        ),
        migrations.AlterField(
            model_name='target',
            name='more',
            field=models.CharField(max_length=2560, verbose_name='responsable_public_ou_dpt_ministeriel_autre'),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=2560, verbose_name='responsable_public'),
        ),
    ]
