# Generated by Django 2.2.5 on 2020-01-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HATVP_app', '0009_auto_20200127_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalinformation',
            options={'verbose_name': 'General Information'},
        ),
        migrations.AddField(
            model_name='activity',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='objet_activite'),
        ),
    ]
